spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb
    username: root
    password: SAIkiran@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


